name: SSL Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ssl_check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Run SSL check script
      run: |
        python SSL_validation_checker.py
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ssl_check_results
        path: ssl_check_results.txt
